/*
 * The MIT License
 *
 * Copyright 2016 Joshua and Dano.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package joshi.astroidz.demo;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author niklas
 */
public final class MotionDisplay extends javax.swing.JPanel {
    
    private static final long serialVersionUID = -6929342652492585794L;
    
    private static final int DELTA = 20;
    
    private final KeyInput input;
    
    private double x;
    private double y;

    /**
     * Creates new form MotionDisplay
     */
    public MotionDisplay() {
        initComponents();
        this.input = new KeyInput();
        setBackground(Color.BLACK);
        new Thread(() -> update()).start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.GREEN);
        g.fillRect((int) this.x, (int) this.y, DELTA, DELTA);
    }

    private void update() {
        long oldTime = System.nanoTime();
        while (true) {
            final long newTime = System.nanoTime();
            final long deltaTime = newTime - oldTime;
            this.x += input.getHorizontalMovement() * (deltaTime / 2000000.0);
            this.y += input.getVerticalMovement()   * (deltaTime / 2000000.0);
            if (this.x < 0) {
                this.x = 0;
            }
            if (this.y < 0) {
                this.y = 0;
            }
            if (this.x > getWidth() - DELTA) {
                this.x = getWidth() - DELTA;
            }
            if (this.y > getHeight() - DELTA) {
                this.y = getHeight() - DELTA;
            }
            oldTime = newTime;
            repaint();
            try {
                Thread.sleep(2);
            } catch (InterruptedException ex) {
                Logger.getLogger(MotionDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    KeyInput getKeyListener() {
        return this.input;
    }
}
